---
- name: Prereq to COntainer Deployment
  hosts: "{{ run_hosts }}"
  gather_facts: false
  #become: true

  tasks:
  - name: Deployment prerequisets
    ansible.builtin.include_role:
      name: prereq-autodeploy-containers
