---
- name: Deploy a containerized webserver
  hosts: "{{ run_hosts }}"
  gather_facts: false
  #become: true

  tasks:
  - name: Deployment prerequisets
    ansible.builtin.include_role:
      name: prereq-autodeploy-containers

  #- name: Deploy the Web Page
  #  ansible.builtin.include_role:
  #    name: deploy_webpage

  #- name: Deploy the Container
  #  ansible.builtin.include_role:
  #    name: deploy_container
