---
# tasks file for roles/deploy_container
- name: Pull an image
  containers.podman.podman_image:
    name: httpd

- name: Re-create a redis container
  containers.podman.podman_container:
    name: sarthak
    image: httpd
    state: started
    detach: true
    exposed_ports:
      - 80
    ports:
      - 4444:80
    volumes: /home/:/usr/local/apache2/htdocs/
